common_hostname: smarthome.fritz.box

swap_enabled: false

locale_languages:
  - de_DE.UTF-8
  - en_GB.UTF-8
  - en_US.UTF-8

ssh_login_user: "{{ vault_ssh_login_user }}"
ssh_login_public_key: "{{ vault_ssh_login_public_key }}"

sshd_allow_users:
  - "{{ vault_ssh_login_user }}"

msmtp_acounts:
  - account: default
    host: smtp.ionos.de
    port: 587
    from: "{{ vault_msmtp_default_user_name }}"
    user: "{{ vault_msmtp_default_user_name }}"
    password: "{{ vault_msmtp_default_password }}"

docker_networks:
  - name: internal
    subnet: 172.18.0.0/16

# https://github.com/influxdata/influxdb/releases
influxdb_docker_image_version: 2.0.7
influxdb_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.influxdb.rule: Host(`influxdb.clubstr.de`)
  traefik.http.routers.influxdb.entrypoints: websecure
  traefik.http.routers.influxdb.service: influxdb-service
  traefik.http.services.influxdb-service.loadbalancer.server.port: 8086
influxdb_docker_network: internal
influxdb_primary_user: "{{ vault_influxdb_primary_user }}"
influxdb_primary_user_password: "{{ vault_influxdb_primary_user_password }}"
influxdb_primary_organization_name: ClubStr
influxdb_primary_bucket_name: General
influxdb_primary_bucket_name_retention_period: 1h
influxdb_buckets:
  - name: Loxone MiniServer
    description: Bucket for Loxone MiniServer
    retention: 0
  - name: Home Assistant
    description: Bucket for Home Assistant
    retention: 14d

# https://github.com/grafana/grafana/releases
grafana_docker_image_version: 7.5.7
grafana_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.grafana.rule: Host(`grafana.clubstr.de`)
  traefik.http.routers.grafana.entrypoints: websecure
  traefik.http.routers.grafana.service: grafana-service
  traefik.http.services.grafana-service.loadbalancer.server.port: 3000
grafana_docker_network: internal
grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_datasources:
  apiVersion: 1
  datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      jsonData:
        version: Flux
        httpMode: POST
        organization: ClubStr
        defaultBucket: General
      secureJsonData:
        token: "{{ grafana_datasources_influxdb_token }}"

# https://github.com/home-assistant/core/releases
home_assistant_docker_image_version: 2021.7.3
home_assistant_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.homeassistant.rule: Host(`homeassistant.clubstr.de`)
  traefik.http.routers.homeassistant.entrypoints: websecure
  traefik.http.routers.homeassistant.service: homeassistant-service
  traefik.http.services.homeassistant-service.loadbalancer.server.port: 8123
home_assistant_docker_network: internal
home_assistant_config_yaml:
  default_config: {}
  http:
    use_x_forwarded_for: true
    trusted_proxies: 172.18.0.0/16

# https://github.com/traefik/traefik/releases
traefik_docker_image_version: 2.4.8
traefik_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.dashboard.rule: Host(`traefik.clubstr.de`)
  traefik.http.routers.dashboard.entrypoints: websecure
  traefik.http.routers.dashboard.service: api@internal
  traefik.http.routers.dashboard.middlewares: auth
  traefik.http.middlewares.auth.basicauth.users: "{{ vault_traefik_api_basic_auth_credentials }}"
traefik_docker_network: internal
traefik_config:
  global:
    checkNewVersion: false
    sendAnonymousUsage: false
  log:
    level: INFO
  accessLog: {}
  api:
    dashboard: true
  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      http:
        tls:
          certResolver: letsencryptresolver
  certificatesResolvers:
    letsencryptresolver:
      acme:
        email: "{{ vault_email_address }}"
        storage: /etc/traefik/acme/acme.json
        # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        dnsChallenge:
          provider: cloudflare
  providers:
    docker:
      exposedByDefault: false
traefik_env_vars:
  CF_DNS_API_TOKEN: "{{ vault_traefik_env_cf_dns_api_token }}"
  CF_ZONE_API_TOKEN: "{{ vault_traefik_env_cf_zone_api_token }}"
