telegraf_docker_image_version: latest
telegraf_docker_memory: 1G
telegraf_docker_labels: {}
telegraf_docker_network: bridge
telegraf_docker_publish_ports: []
  # - 8080:8080
  # - 8094:8094

telegraf_etc_path: /etc/telegraf

# https://docs.influxdata.com/telegraf/latest/administration/configuration/
telegraf_config: |
  # Telegraf Configuration

  # Configuration for telegraf agent
  [agent]
    interval = "20s"

  # Read metrics about cpu usage
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/cpu/README.md
  [[inputs.cpu]]

  # Read metrics about disk usage by mount point
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/disk/README.md
  [[inputs.disk]]

  # Read metrics about disk IO by device
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/diskio/README.md
  [[inputs.diskio]]

  # Generic HTTP write listener
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/http_listener_v2/README.md
  [[inputs.http_listener_v2]]
    service_address = ":8080"

  # Get kernel statistics from /proc/stat
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/kernel/README.md
  [[inputs.kernel]]

  # Read metrics about memory usage
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/mem/README.md
  [[inputs.mem]]

  # Read metrics about network interface usage
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/net/NET_README.md
  [[inputs.net]]

  # Get the number of processes and group them by status
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/processes/README.md
  [[inputs.processes]]

  # Generic socket listener capable of handling multiple socket types.
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/socket_listener/README.md
  [[inputs.socket_listener]]
    service_address = "udp://:8094"

  # Read metrics about swap memory usage
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/swap/README.md
  [[inputs.swap]]

  # Read metrics about system load & uptime
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/system/README.md
  [[inputs.system]]

  # Gather systemd units state
  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/inputs/systemd_units/README.md
  [[inputs.systemd_units]]

  # https://github.com/influxdata/telegraf/blob/release-1.19/plugins/outputs/influxdb_v2/README.md
  [[outputs.influxdb_v2]]
    urls = ["http://influxdb:8086"]
    organization = "my-org"
    bucket = "my-bucket"

telegraf_env_vars: {}
