- hosts: smart_home
  vars:
    ansible_user: pi
    ansible_password: raspberry
  tasks:
    - name: Install parted package
      ansible.builtin.apt:
        name: parted
        state: present
        update_cache: true

    - name: Read device information
      community.general.parted:
        device: /dev/sda
        unit: MiB
      register: sda_info

    - name: Remove all partitions from disk
      community.general.parted:
        device: /dev/sda
        number: "{{ item.num }}"
        state: absent
      loop: "{{ sda_info.partitions }}"

    # Using fdisk because parted v3.2-25 performs on Debian Buster not idempotent
    - name: Create partition on disk
      ansible.builtin.shell:
        cmd: echo -e "o\nn\np\n1\n81920\n\nw" | fdisk /dev/sda

    - name: Create ext4 filesystem on partition
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda1
        state: present
