roles:
  # https://galaxy.ansible.com/escalate/cmdline
  - name: cmdline
    src: escalate.cmdline
    version: v3.0.0

  # https://galaxy.ansible.com/escalate/common
  - name: common
    src: escalate.common
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/swap
  - name: swap
    src: escalate.swap
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/cron
  - name: cron
    src: escalate.cron
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/locale
  - name: locale
    src: escalate.locale
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/systemd_timesyncd
  - name: systemd_timesyncd
    src: escalate.systemd_timesyncd
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/sshd
  - name: sshd
    src: escalate.sshd
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/ssh_login
  - name: ssh_login
    src: escalate.ssh_login
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/msmtp
  - name: msmtp
    src: escalate.msmtp
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/smb_mount
  - name: smb_mount
    src: escalate.smb_mount
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/remote_backup
  - name: remote_backup
    src: escalate.remote_backup
    version: v2.0.0

  # https://galaxy.ansible.com/escalate/docker
  - name: docker
    src: escalate.docker
    version: v3.1.0

  # https://galaxy.ansible.com/escalate/influxdb
  - name: influxdb
    src: escalate.influxdb
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/grafana
  - name: grafana
    src: escalate.grafana
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/home_assistant
  - name: home_assistant
    src: escalate.home_assistant
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/telegraf
  - name: telegraf
    src: escalate.telegraf
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/loki
  - name: loki
    src: escalate.loki
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/promtail
  - name: promtail
    src: escalate.promtail
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/traefik
  - name: traefik
    src: escalate.traefik
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/coredns
  - name: coredns
    src: escalate.coredns
    version: v2.1.0

  # https://galaxy.ansible.com/escalate/luxtronik
  - name: luxtronik
    src: escalate.luxtronik
    version: v2.0.0

collections:
  # https://galaxy.ansible.com/ansible/posix
  - name: ansible.posix
    version: 2.1.0

  # https://galaxy.ansible.com/community/docker
  - name: community.docker
    version: 4.6.1

  # https://galaxy.ansible.com/community/general
  - name: community.general
    version: 11.1.0
