roles:
  - src: escalate.common
    name: common

  - src: escalate.timesyncd
    name: timesyncd

  - src: escalate.sshd
    name: sshd

  - src: escalate.ssh_login
    name: ssh_login

  - src: escalate.msmtp
    name: msmtp

  - src: escalate.docker
    name: docker

  - src: escalate.influxdb
    name: influxdb

  - src: escalate.grafana
    name: grafana

  - src: escalate.traefik
    name: traefik

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
