roles:
  - name: common
    src: escalate.common

  - name: timesyncd
    src: escalate.timesyncd

  - name: sshd
    src: escalate.sshd

  - name: ssh_login
    src: escalate.ssh_login

  - name: msmtp
    src: escalate.msmtp

  - name: docker
    src: escalate.docker

  - name: influxdb
    src: escalate.influxdb

  - name: grafana
    src: escalate.grafana

  - name: traefik
    src: escalate.traefik

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
