roles:
  # https://galaxy.ansible.com/ui/standalone/roles/escalate/luxtronik/
  - name: luxtronik
    src: escalate.luxtronik
    version: v2.0.0

collections:
  # https://galaxy.ansible.com/ui/repo/published/escalate/raspberry/
  - name: escalate.raspberry
    version: 1.20.0
