# Updating: https://www.raspberrypi.org/documentation/raspbian/updating.md

- name: Update Raspberry Pi OS
  hosts: all
  tasks:
    - name: Update Raspberry Pi OS
      ansible.builtin.apt:
        upgrade: full
        update_cache: true

    - name: Reboot Raspberry Pi
      ansible.builtin.reboot:
