- hosts: all
  tasks:
    - name: Create empty kernel cmdline file
      ansible.builtin.copy:
        dest: /boot/cmdline.txt
        content: ""

    - name: Create missing groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - spi
        - gpio
        - i2c
