- name: Vargrant
  hosts: all
  tasks:
    - name: Create empty kernel cmdline file
      ansible.builtin.copy:
        content: ""
        dest: /boot/cmdline.txt
        mode: "0755"
        owner: root
        group: root

    - name: Create special groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - spi
        - gpio
        - i2c
