- name: Prepare
  hosts: all
  tasks:
    - name: Create cmdline.txt
      ansible.builtin.copy:
        dest: /boot/cmdline.txt
        content: "console=serial0,115200 console=tty1 root=UUID=49a6dc8a-761b-418a-bb46-344127dcc1a0 rootfstype=ext4 fsck.repair=yes rootwait quiet init=/usr/lib/raspi-config/init_resize.sh"
