- name: Prepare
  hosts: all
  vars:
    docker_daemon_json:
      live-restore: true
      log-driver: local
      log-opts:
        max-size: 100m
      storage-driver: vfs
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
  tasks:
    - name: Create network
      command:
        cmd: docker network create internal
