# https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/
docker_version: 25.0.3-1
docker_containerd_version: 1.6.28-1
# https://pypi.org/project/docker/
docker_python_version: 5.0.3

# https://docs.docker.com/engine/reference/commandline/system_prune/
docker_system_prune_cron: true

# https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
docker_daemon_json:
  live-restore: true
  log-driver: local
  log-opts:
    max-size: 100m
    max-file: "5"

# https://docs.docker.com/engine/reference/commandline/network_create/
docker_networks: []
  # - name: internal
  #   subnet: 172.25.0.0/16
