- name: Converge
  hosts: all
  vars:
    promtail_docker_image_version: latest
    promtail_docker_memory: 1G
    promtail_docker_labels:
      maintainer: me@example.com
    promtail_docker_network: internal
    promtail_docker_publish_ports:
      - 127.0.0.1:9080:9080
    promtail_data_path: /var/lib/promtail
    promtail_etc_path: /etc/promtail
    promtail_config:
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      positions:
        filename: /var/lib/promtail/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                host: "{{ inventory_hostname }}"
                __path__: /var/log/*log
    promtail_config_type: static
    promtail_env_vars:
      APP_TEST_ENV: "true"
  roles:
    - role: ansible-raspberry-promtail-docker
      tags: promtail
