- name: Prepare
  hosts: all
  tasks:
    - name: Install openssh-server package
      ansible.builtin.apt:
        name: openssh-server
        state: present
        update_cache: true

    - name: Start and enable sshd service
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
        daemon_reload: true
