- name: Prepare
  hosts: all
  tasks:
    - name: Remove blocking condition from systemd-timesyncd unit file
      community.general.ini_file:
        path: /lib/systemd/system/systemd-timesyncd.service
        section: Unit
        option: ConditionVirtualization
        state: absent
    - name: Force systemd to reread systemd-timesync unit file
      ansible.builtin.systemd:
        daemon_reload: true
