- name: Side Effect
  hosts: all
  tasks:
    - name: Remove blocking condition from systemd-timesyncd unit file
      community.general.ini_file:
        path: /lib/systemd/system/systemd-timesyncd.service
        section: Unit
        option: ConditionVirtualization
        state: absent
    - name: Restart systemd-timesyncd service
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted
        daemon_reload: true
