- name: Install package
  ansible.builtin.apt:
    name: dhcpcd5
    state: present
    update_cache: true

- name: Create service configuration
  ansible.builtin.template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcpcd service

- name: Start and enable service
  ansible.builtin.systemd:
    name: dhcpcd
    state: started
    enabled: true
    daemon_reload: true
