galaxy_info:
  role_name: dhcpcd
  namespace: escalate
  author: Felix Boerner
  description: Manage dhcpcd on Raspberry Pi OS
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - dhcpcd
    - dhcp
dependencies: []
