- name: Converge
  hosts: all
  vars:
    telegraf_docker_image_version: latest
    telegraf_docker_memory: 1G
    telegraf_docker_labels:
      maintainer: me@example.com
    telegraf_docker_network: internal
    telegraf_docker_publish_ports:
      - 8080:8080
      - 9273:9273
    telegraf_etc_path: /etc/telegraf
    telegraf_config: |
      [[inputs.http_listener_v2]]
        service_address = ":8080"
        data_format = "influx"

      [[outputs.prometheus_client]]
        listen = ":9273"
        metric_version = 2
        flush_interval = "10ms"
        flush_jitter = "10ms"
        metric_batch_size = 1
    telegraf_env_vars:
      INFLUX_SKIP_DATABASE_CREATION: "true"
  roles:
    - role: ansible-raspberry-telegraf-docker
      tags: telegraf
