- name: Converge
  hosts: all
  vars:
    home_assistant_docker_image_version: latest
    home_assistant_docker_memory: 1G
    home_assistant_docker_labels:
      maintainer: me@example.com
    home_assistant_docker_network: internal
    home_assistant_data_path: /var/lib/home-assistant
    home_assistant_additional_user_groups:
      - tty
    home_assistant_env_vars:
      PUID: 10200
      PGID: 0
      PACKAGES: iputils
    home_assistant_config:
      default_config: {}
  roles:
    - role: ansible-raspberry-home-assistant-docker
      tags: homeassistant
