traefik_docker_image_version: latest
traefik_docker_memory: 1G
traefik_docker_labels: {}
traefik_docker_network: bridge
traefik_docker_publish_ports:
  # http
  - 80:80
  # https
  - 443:443

traefik_data_path: /var/lib/traefik
traefik_etc_path: /etc/traefik

# https://doc.traefik.io/traefik/reference/static-configuration/file/
traefik_config:
  global:
    checkNewVersion: false
    sendAnonymousUsage: false
  log:
    level: INFO
  accessLog: {}
  api:
    dashboard: true
  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"
      # http:
      #   tls:
      #     certResolver: letsencryptresolver
  # certificatesResolvers:
  #   letsencryptresolver:
  #     acme:
  #       email: me@example.com
  #       storage: /etc/traefik/acme/acme.json
  #       caServer: https://acme-staging-v02.api.letsencrypt.org/directory
  #       dnsChallenge:
  #         provider: cloudflare
  providers:
    docker:
      exposedByDefault: false

# https://doc.traefik.io/traefik/reference/static-configuration/env/
traefik_env_vars: {}
