galaxy_info:
  role_name: sshd
  namespace: escalate
  author: Felix Boerner
  description: Manage sshd on Raspberry Pi OS
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - systemd
    - openssh
    - sshd
dependencies: []
