# root= parameter is ignored and taken from Raspberry Pi
cmdline_parameters:
  - console=serial0,115200
  - console=tty1
  - root=PARTUUID=51821e2e-02
  - rootfstype=ext4
  - elevator=deadline
  - fsck.repair=yes
  - rootwait
