ssh_login_user: "{{ vault_ssh_login_user }}"
ssh_login_public_key: "{{ vault_ssh_login_public_key }}"

sshd_allow_users:
  - "{{ vault_ssh_login_user }}"

msmtp_acounts:
  - account: default
    host: smtp.ionos.de
    port: 587
    from: "{{ vault_msmtp_default_user_name }}"
    user: "{{ vault_msmtp_default_user_name }}"
    password: "{{ vault_msmtp_default_password }}"

# https://github.com/influxdata/influxdb/releases
influxdb_docker_image_version: 2.0.6
influxdb_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.influxdb.rule: Host(`influxdb.clubstr.de`)
  traefik.http.routers.influxdb.entrypoints: websecure
  traefik.http.routers.influxdb.service: influxdb-service
  traefik.http.services.influxdb-service.loadbalancer.server.port: 8086
influxdb_primary_user: "{{ vault_influxdb_primary_user }}"
influxdb_primary_user_password: "{{ vault_influxdb_primary_user_password }}"
influxdb_primary_organization_name: ClubStr
influxdb_primary_bucket_name: General
influxdb_primary_bucket_name_retention_period: 1h
influxdb_buckets:
  - name: Loxone MiniServer
    description: Bucket for Loxone MiniServer
    retention: 0
  - name: Home Assistant
    description: Bucket for Home Assistant
    retention: 14d

# https://github.com/grafana/grafana/releases
grafana_docker_image_version: 7.5.6
grafana_docker_labels:
  traefik.enable: "true"
  traefik.http.routers.grafana.rule: Host(`grafana.clubstr.de`)
  traefik.http.routers.grafana.entrypoints: websecure
  traefik.http.routers.grafana.service: grafana-service
  traefik.http.services.grafana-service.loadbalancer.server.port: 3000
grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# https://github.com/traefik/traefik/releases
traefik_docker_image_version: 2.4.8
