galaxy_info:
  role_name: cmdline
  namespace: escalate
  author: Felix Boerner
  description: Manage Linux kernel command line on Raspberry Pi OS
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - cmdline
    - linux
    - kernel
dependencies: []
