- name: Converge
  hosts: all
  vars:
    docker_daemon_json:
      live-restore: true
      log-driver: local
      log-opts:
        max-size: 100m
    docker_networks:
      - name: internal
        subnet: 172.25.0.0/16
  roles:
    - role: ansible-raspberry-docker
      tags: docker
