galaxy_info:
  role_name: remote_backup
  namespace: escalate
  author: Felix Boerner
  description: Manage remote backup job configuration on Raspberry Pi OS
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - raspberry
    - pi
    - raspberrypi
    - remote
    - backup
    - onsite
    - offsite
    - rsync
    - mount
dependencies: []
