- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ common_install_packages }}"
    state: present
    update_cache: true

- name: Remove packages
  ansible.builtin.apt:
    name: "{{ common_remove_packages }}"
    state: absent
    update_cache: true
