- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - msmtp
      - msmtp-mta

- name: Create service configuration
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: 0640
  no_log: true

- name: Validate service configuration
  ansible.builtin.command:
    cmd: msmtp --serverinfo
  when: msmtp_acounts | length
  changed_when: false
