- name: Install package
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present
    update_cache: true

- name: Configure NTP servers
  community.general.ini_file:
    path: /etc/systemd/timesyncd.conf
    section: Time
    option: NTP
    value: "{{ systemd_timesyncd_ntp_servers }}"
    no_extra_spaces: true
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-timesyncd service

- name: Configure Fallback NTP servers
  community.general.ini_file:
    path: /etc/systemd/timesyncd.conf
    section: Time
    option: FallbackNTP
    value: "{{ systemd_timesyncd_fallback_ntp_servers }}"
    no_extra_spaces: true
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-timesyncd service

- name: Start service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    daemon_reload: true
  tags: molecule-notest

- name: Enable service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    daemon_reload: true
