- name: Create application user
  ansible.builtin.user:
    name: telegraf
    uid: 10400
    group: root
    create_home: false
    shell: /sbin/nologin

- name: Create config directory
  ansible.builtin.file:
    path: "{{ telegraf_etc_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create service configuration
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_etc_path }}/telegraf.conf"
    owner: root
    group: root
    mode: 0644
  no_log: true
  notify: Restart telegraf service

- name: Define environment variables
  ansible.builtin.template:
    src: telegraf.env.j2
    dest: /etc/telegraf.env
    owner: root
    group: root
    mode: 0644
  notify: Restart telegraf service

- name: Define Docker container labels
  ansible.builtin.template:
    src: telegraf.label.j2
    dest: /etc/telegraf.label
    owner: root
    group: root
    mode: 0644
  notify: Restart telegraf service

- name: Pull Docker image
  community.docker.docker_image:
    name: "telegraf:{{ telegraf_docker_image_version }}"
    source: pull

- name: Create systemd service
  ansible.builtin.template:
    src: telegraf.service.j2
    dest: /etc/systemd/system/telegraf.service
    owner: root
    group: root
    mode: 0644
  notify: Restart telegraf service

- name: Start and enable service
  ansible.builtin.systemd:
    name: telegraf
    state: started
    enabled: true
    daemon_reload: true
